---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: "Include organicveggie.calibre_web_docker"
      ansible.builtin.include_role:
        name: "organicveggie.calibre_web_docker"
